// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_c6h2oDfOxXUwmu6WoHzU3T0_2OWdUCA',
    appId: '1:211816811397:web:272a5621713e62712052ec',
    messagingSenderId: '211816811397',
    projectId: 'taskapp-e206b',
    authDomain: 'taskapp-e206b.firebaseapp.com',
    storageBucket: 'taskapp-e206b.appspot.com',
    measurementId: 'G-10T1QFM4Q1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfS_-aNWAqgJEtmPmf-hfZOZhzHDWjUmA',
    appId: '1:211816811397:android:775502d1a7b47bd62052ec',
    messagingSenderId: '211816811397',
    projectId: 'taskapp-e206b',
    storageBucket: 'taskapp-e206b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1DnLvUc_cwyA--V13PNu3jheXdyq5gDI',
    appId: '1:211816811397:ios:e84e3db13810a29d2052ec',
    messagingSenderId: '211816811397',
    projectId: 'taskapp-e206b',
    storageBucket: 'taskapp-e206b.appspot.com',
    iosBundleId: 'com.example.todolistApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1DnLvUc_cwyA--V13PNu3jheXdyq5gDI',
    appId: '1:211816811397:ios:4484e8e5e451b76c2052ec',
    messagingSenderId: '211816811397',
    projectId: 'taskapp-e206b',
    storageBucket: 'taskapp-e206b.appspot.com',
    iosBundleId: 'com.example.todolistApp.RunnerTests',
  );
}
